[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapage = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/chuongtang/.config/solana/id.json"

[scripts]
test = "node tests/solanapage.js"
